### ISSUE TITLE
Error export_to_excel(ec2_dict,'ec2') when EC2 instance is terminated and doesn't have ENI

### ISSUE THREAD

**Issue by chnacib** [chnacib/aws-sdk-hermes#7]
Logs

```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    ec2.run()
  File "/app/src/services/ec2.py", line 229, in run
    export_to_excel(ec2_dict, 'ec2')
  File "/app/src/common/excel.py", line 19, in export_to_excel
    df = pd.DataFrame(excel_data)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 120, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 674, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
```

**Comment by chnacib** [comment]
Fixed
